version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - web

  peet-tls:
    image: peet-tls
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/certs/:/app/certs
      - ${PWD}/config.json:/app/config.json
      - ${PWD}/blockedIPs:/app/blockedIPs
    networks:
      - web

networks:
  web:
    external: true
